# Generated by Django 4.1.7 on 2023-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_rule_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='applied_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='applied_rules',
            field=models.ManyToManyField(default=None, to='blocks.rule'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rule_strings',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='keywordrule',
            name='similarity_threshold',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
