# Generated by Django 4.1.7 on 2023-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_remove_rule_applied_answers_answer_applied_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordrule',
            name='relevant_keywords',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
