# Generated by Django 4.1.7 on 2023-03-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_keywordrule_relevant_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceSimilarityRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.rule')),
                ('sentence', models.CharField(max_length=2048)),
                ('similarity_threshold', models.FloatField(blank=True, default=0.8, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('blocks.rule',),
        ),
    ]
