# Generated by Django 4.1.7 on 2023-03-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_answerlengthrule_alter_sentencesimilarityrule_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTGradeAndFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('prompt', models.TextField()),
                ('prompt_type', models.CharField(max_length=200)),
                ('trial_run_number', models.IntegerField()),
                ('answer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.answer')),
            ],
        ),
    ]
