# Generated by Django 4.1.7 on 2023-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_chatgptgradeandfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptgradeandfeedback',
            name='openai_model',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
