# Generated by Django 4.1.7 on 2023-04-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_chatgptgradeandfeedback_openai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.rule'),
        ),
    ]
