# Generated by Django 4.1.7 on 2023-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_rule_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='outlier_score',
            field=models.FloatField(default=0.0),
        ),
    ]
