# Generated by Django 4.1.7 on 2023-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_answer_outlier_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='polarity',
            field=models.CharField(blank=True, default='positive', max_length=200, null=True),
        ),
    ]
