# Generated by Django 4.1.7 on 2023-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_rule_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordrule',
            name='negative_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='keywordrule',
            name='positive_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='sentencesimilarityrule',
            name='negative_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='sentencesimilarityrule',
            name='positive_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
