# Generated by Django 4.1.7 on 2023-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0013_keywordrule_negative_examples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordrule',
            name='negative_examples',
        ),
        migrations.RemoveField(
            model_name='keywordrule',
            name='positive_examples',
        ),
        migrations.RemoveField(
            model_name='sentencesimilarityrule',
            name='negative_examples',
        ),
        migrations.RemoveField(
            model_name='sentencesimilarityrule',
            name='positive_examples',
        ),
        migrations.AddField(
            model_name='rule',
            name='negative_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='rule',
            name='positive_examples',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
