# Generated by Django 4.1.7 on 2023-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0014_remove_keywordrule_negative_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_concepts',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
