# Generated by Django 4.1.7 on 2023-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_question_related_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='concept_scores',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
