# Generated by Django 4.1.7 on 2023-05-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0017_conceptsimilarityrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster_id', models.IntegerField(default=0)),
                ('cluster_description', models.TextField(blank=True, null=True)),
                ('cluster_grade', models.FloatField(blank=True, null=True)),
                ('cluster_feedback', models.TextField(blank=True, null=True)),
                ('applied_rules', models.ManyToManyField(default=None, to='blocks.rule')),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.question')),
            ],
            options={
                'ordering': ['question__id', 'cluster_id'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='cluster',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.cluster'),
        ),
    ]
