# Generated by Django 4.1.7 on 2023-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0018_cluster_answer_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='override_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='override_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
