# Generated by Django 4.1.7 on 2023-06-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0020_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reasoning_dict', models.TextField()),
                ('feedback', models.TextField()),
                ('answer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.answer')),
            ],
        ),
    ]
