# Generated by Django 4.1.7 on 2023-06-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0021_answertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertag',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.question'),
        ),
    ]
