# Generated by Django 4.1.7 on 2023-07-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0022_answertag_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_dict', models.TextField()),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.question')),
            ],
        ),
    ]
