# Generated by Django 4.1.7 on 2023-07-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0023_rubricdict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RubricDict',
            new_name='RubricList',
        ),
        migrations.RenameField(
            model_name='rubriclist',
            old_name='rubric_dict',
            new_name='rubric_list',
        ),
    ]
