# Generated by Django 4.1.7 on 2023-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0024_rename_rubricdict_rubriclist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertag',
            options={'ordering': ['question__id', 'answer__id', 'tag']},
        ),
        migrations.RemoveField(
            model_name='answertag',
            name='feedback',
        ),
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('reasoning_dict', models.TextField()),
                ('answer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.answer')),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.question')),
            ],
            options={
                'ordering': ['question__id', 'answer__id'],
            },
        ),
    ]
