# Generated by Django 4.1.7 on 2023-07-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0025_alter_answertag_options_remove_answertag_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertag',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
