# Generated by Django 4.1.7 on 2023-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0026_answertag_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='chi_cluster_id',
            field=models.IntegerField(default=0),
        ),
    ]
