# Generated by Django 4.1.7 on 2023-08-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0027_answer_chi_cluster_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertag',
            options={'ordering': ['question__id', 'answer__id', 'numeric_tag', 'tag']},
        ),
        migrations.AddField(
            model_name='answertag',
            name='numeric_tag',
            field=models.IntegerField(default=0),
        ),
    ]
